const pb = new PocketBase(window.REFIND_CONFIG?.apiUrl || 'http://127.0.0.1:8090');
pb.autoCancellation(false);
const KEY='refind_device_v3';
const $=id=>document.getElementById(id);
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{deviceId:null,name:'',lost:false};
let map=null,marker=null,accuracyCircle=null,unsubscribe=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3500)}
function fmt(n){return Number(n).toFixed(5)}
function formatLocation(d){return d?.lastLatitude==null?'Not available':`${fmt(d.lastLatitude)}, ${fmt(d.lastLongitude)}`}
function initMap(){if(map||!window.L)return;map=L.map('mapArea',{zoomControl:true,attributionControl:true}).setView([-1.2864,36.8172],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map)}
function drawLocation(d,fit=true){if(d?.lastLatitude==null||d?.lastLongitude==null)return;initMap();const point=[d.lastLatitude,d.lastLongitude];if(!marker)marker=L.marker(point).addTo(map);else marker.setLatLng(point);marker.bindPopup(`<strong>${escapeHtml(d.name||'Registered phone')}</strong><br>Last seen: ${d.lastSeen?new Date(d.lastSeen).toLocaleString():'Unknown'}`);if(!accuracyCircle)accuracyCircle=L.circle(point,{radius:Number(d.lastAccuracy||50),weight:1,fillOpacity:.12}).addTo(map);else accuracyCircle.setLatLng(point).setRadius(Number(d.lastAccuracy||50));if(fit)map.setView(point,16)}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const connected=pb.authStore.isValid;$('deviceName').textContent=state.name||'No device selected';$('heroDeviceName').textContent=state.name||'No device selected';$('deviceMeta').textContent=connected?'Cloud account connected':'Sign in to sync your devices';$('deviceStatus').textContent=state.lost?'LOST MODE':state.deviceId?'PROTECTED':'OFFLINE';$('syncPill').textContent=connected?'Realtime cloud sync':'Sign in required';if($('deviceSelect'))$('deviceSelect').value=state.deviceId||''}
function applyDevice(d,fit=true){if(!d)return;state.name=d.name||'';state.lost=d.status==='lost';state.deviceId=d.id;save();render();$('lastLocation').textContent=formatLocation(d);$('heroLocation').textContent=formatLocation(d);$('mapTitle').textContent=d.lastLatitude==null?'Waiting for location':'Phone location updated';$('battery').textContent=d.battery==null?'Unknown':`${Math.round(d.battery)}%`;$('lastUpdate').textContent=d.lastSeen?new Date(d.lastSeen).toLocaleString():'Never';$('commandStatus').textContent=d.lastCommand?`Last command: ${d.lastCommand}${d.lastCommandAt?' • '+new Date(d.lastCommandAt).toLocaleTimeString():''}`:'No command activity';if(d.lastLatitude!=null)drawLocation(d,fit)}
async function loadDevices(){if(!pb.authStore.isValid)return;try{const list=await pb.collection('devices').getFullList({sort:'name'});const sel=$('deviceSelect');if(sel){sel.innerHTML=list.length?list.map(d=>`<option value="${escapeHtml(d.id)}">${escapeHtml(d.name)}</option>`).join(''):'<option value="">No devices</option>';sel.value=state.deviceId&&list.some(d=>d.id===state.deviceId)?state.deviceId:(list[0]?.id||'');if(sel.value){state.deviceId=sel.value;save();const d=list.find(x=>x.id===sel.value);applyDevice(d,false);subscribeDevice();loadHistory()}}}catch(e){toast('Could not load your devices.')}}
async function refreshDevice(){if(!pb.authStore.isValid||!state.deviceId)return;try{const d=await pb.collection('devices').getOne(state.deviceId);applyDevice(d);subscribeDevice();loadHistory()}catch(e){toast('Could not load the selected device.')}}
function subscribeDevice(){if(!state.deviceId||!pb.authStore.isValid)return;if(unsubscribe){unsubscribe();unsubscribe=null}pb.collection('devices').subscribe(state.deviceId,e=>{if(['update','create'].includes(e.action))applyDevice(e.record,false)}).then(()=>{unsubscribe=()=>pb.collection('devices').unsubscribe(state.deviceId).catch(()=>{})}).catch(()=>{})}
async function loadHistory(){if(!state.deviceId||!pb.authStore.isValid)return;try{const rows=await pb.collection('locations').getList(1,30,{filter:`device="${state.deviceId}"`,sort:'-created'});const box=$('historyList');if(box)box.innerHTML=rows.items.length?rows.items.map(x=>`<div class="history-row"><span>${new Date(x.created).toLocaleString()}</span><strong>${Number(x.latitude).toFixed(5)}, ${Number(x.longitude).toFixed(5)}</strong><small>±${Math.round(Number(x.accuracy||0))}m${x.battery!=null?' • '+Math.round(x.battery)+'%':''}</small></div>`).join(''):'<p class="muted">No location history yet.</p>'}catch(e){}}
function authPanel(){if(document.getElementById('authPanel'))return;const panel=document.createElement('div');panel.id='authPanel';panel.className='glass';panel.style.cssText='position:fixed;inset:auto 20px 20px auto;z-index:50;width:min(360px,calc(100vw - 40px));padding:20px;box-shadow:0 20px 60px #0008';panel.innerHTML=`<h3>ReFind account</h3><p id="authStatus">Sign in to sync your phones.</p><input id="authEmail" type="email" placeholder="Email" style="width:100%;padding:12px;margin:6px 0"><input id="authPass" type="password" placeholder="Password" style="width:100%;padding:12px;margin:6px 0"><div style="display:flex;gap:8px;margin-top:8px"><button class="btn primary" id="loginBtn">Sign in</button><button class="btn secondary" id="signupBtn">Create account</button></div>`;document.body.appendChild(panel);$('loginBtn').onclick=()=>authenticate(false);$('signupBtn').onclick=()=>authenticate(true)}
async function authenticate(create){const email=$('authEmail').value.trim(),password=$('authPass').value;if(!email||password.length<8){toast('Use an email and a password of at least 8 characters.');return}try{if(create)await pb.collection('users').create({email,password,passwordConfirm:password});await pb.collection('users').authWithPassword(email,password);$('authStatus').textContent=`Signed in as ${pb.authStore.record.email}`;toast('ReFind account connected.');await loadDevices()}catch(e){toast(e?.response?.message||'Authentication failed.')}}
async function register(){if(!pb.authStore.isValid){authPanel();toast('Sign in first.');return}const name=prompt('Device name, e.g. “Vincent’s Phone”');if(!name?.trim())return;const deviceId=crypto.randomUUID();try{const d=await pb.collection('devices').create({owner:pb.authStore.record.id,deviceId,name:name.trim(),platform:'web',status:'protected'});applyDevice(d);toast('Device registered.')}catch(e){toast(e?.response?.message||'Could not register device.')}}
async function updateLocation(){if(!pb.authStore.isValid||!state.deviceId){register();return}if(!navigator.geolocation){toast('This browser does not provide geolocation.');return}navigator.geolocation.getCurrentPosition(async pos=>{try{await pb.collection('devices').update(state.deviceId,{lastLatitude:pos.coords.latitude,lastLongitude:pos.coords.longitude,lastAccuracy:pos.coords.accuracy,lastSeen:new Date().toISOString(),lastHeartbeat:new Date().toISOString()});await pb.collection('locations').create({device:state.deviceId,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy});toast(`Location sent. Accuracy ~${Math.round(pos.coords.accuracy)}m.`);await loadHistory()}catch(e){toast('Location was captured but could not be uploaded.')}},err=>toast(err.code===1?'Location permission was denied.':err.message),{enableHighAccuracy:true,timeout:15000,maximumAge:30000})}
async function lostMode(){if(!state.deviceId){register();return}try{state.lost=!state.lost;await pb.collection('devices').update(state.deviceId,{status:state.lost?'lost':'protected'});toast(state.lost?'Lost Mode enabled.':'Lost Mode disabled.')}catch(e){toast('Could not change Lost Mode.')}}
async function ring(){if(!state.deviceId){register();return}try{await pb.collection('devices').update(state.deviceId,{ringRequestedAt:new Date().toISOString(),lastCommand:'ring',lastCommandAt:new Date().toISOString()});toast('Ring command sent. Waiting for the phone to acknowledge it.')}catch(e){toast('Could not send ring command.')}}
$('locateBtn').addEventListener('click',updateLocation);$('ringBtn').addEventListener('click',ring);$('lostBtn').addEventListener('click',lostMode);$('deviceSelect')?.addEventListener('change',async e=>{state.deviceId=e.target.value;save();await refreshDevice()});document.querySelector('[data-scroll="devices"]').addEventListener('click',()=>document.getElementById('devices').scrollIntoView());document.querySelector('[data-scroll="recovery"]').addEventListener('click',()=>document.getElementById('recovery').scrollIntoView());const installBtn=$('installBtn');let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;installBtn.hidden=true}});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));pb.authStore.onChange(()=>{render();loadDevices()});initMap();if(pb.authStore.isValid){authPanel();loadDevices()}render();